name: Docker CI/CD

on:
  push:
    branches:
      - main  # Change this branch according to your setup

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
        shell: bash

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t your-dockerhub-username/hmem-img:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/hmem-img:latest .
      - name: Cleanup
        run: |
          docker buildx rm
